"""Push generated Terraform to a GitHub repository using the REST API."""
import base64
from typing import List, Optional, Tuple
import httpx

from app.models.schemas import (
    GithubPushRequest,
    GithubPushResponse,
    TerraformFile,
)


GITHUB_API = "https://api.github.com"


class GithubError(Exception):
    pass


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "ArchLens",
    }


def _resolve_owner_repo(client: httpx.Client, token: str, repo_name: str) -> Tuple[str, str]:
    """Return (owner, repo). repo_name may be 'name' or 'owner/name'."""
    if "/" in repo_name:
        owner, repo = repo_name.split("/", 1)
        return owner.strip(), repo.strip()
    # Get authenticated user
    r = client.get(f"{GITHUB_API}/user", headers=_headers(token))
    if r.status_code != 200:
        raise GithubError(f"Failed to authenticate with GitHub: {r.status_code} {r.text}")
    return r.json()["login"], repo_name.strip()


def _repo_exists(client: httpx.Client, token: str, owner: str, repo: str) -> Optional[dict]:
    r = client.get(f"{GITHUB_API}/repos/{owner}/{repo}", headers=_headers(token))
    if r.status_code == 200:
        return r.json()
    if r.status_code == 404:
        return None
    raise GithubError(f"Failed to check repo: {r.status_code} {r.text}")


def _create_repo(
    client: httpx.Client, token: str, repo: str, private: bool, owner_is_user: bool, owner: str
) -> dict:
    payload = {
        "name": repo,
        "private": private,
        "auto_init": True,
        "description": "Generated by ArchLens — Terraform IaC for cloud architecture",
    }
    url = (
        f"{GITHUB_API}/user/repos"
        if owner_is_user
        else f"{GITHUB_API}/orgs/{owner}/repos"
    )
    r = client.post(url, headers=_headers(token), json=payload)
    if r.status_code not in (200, 201):
        raise GithubError(f"Failed to create repo: {r.status_code} {r.text}")
    return r.json()


def _put_file(
    client: httpx.Client,
    token: str,
    owner: str,
    repo: str,
    path: str,
    content: str,
    branch: str,
    message: str,
) -> dict:
    """Create or update a single file via the contents API."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}"

    # Look up existing SHA (needed when updating)
    existing_sha = None
    r_get = client.get(url, headers=_headers(token), params={"ref": branch})
    if r_get.status_code == 200:
        existing_sha = r_get.json().get("sha")

    body = {
        "message": message,
        "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
        "branch": branch,
    }
    if existing_sha:
        body["sha"] = existing_sha

    r = client.put(url, headers=_headers(token), json=body)
    if r.status_code not in (200, 201):
        raise GithubError(f"Failed to write {path}: {r.status_code} {r.text}")
    data = r.json()
    return {
        "path": path,
        "sha": data.get("content", {}).get("sha", ""),
        "html_url": data.get("content", {}).get("html_url", ""),
    }


def _build_readme(
    files: List[TerraformFile],
    cloud_hint: str = "",
    extra: Optional[str] = None,
) -> str:
    file_list = "\n".join(f"- `{f.filename}` — {f.description or ''}" for f in files)
    extra_block = f"\n\n## Notes\n\n{extra}\n" if extra else ""
    return f"""# ArchLens — Terraform IaC

Generated by [ArchLens](https://github.com/) — intelligent architecture diagram analyzer.

{cloud_hint}

## Files

{file_list}

## Quick start

```bash
cd terraform
terraform init
terraform plan
terraform apply
```

> ⚠️ Review variables and provider credentials before applying.{extra_block}
"""


def push_to_github(req: GithubPushRequest) -> GithubPushResponse:
    if not req.token:
        raise GithubError("GitHub token is required")
    if not req.files:
        raise GithubError("No files to push")

    with httpx.Client(timeout=30.0) as client:
        owner, repo = _resolve_owner_repo(client, req.token, req.repo_name)

        # Determine if owner is the authenticated user (decides create endpoint)
        me = client.get(f"{GITHUB_API}/user", headers=_headers(req.token))
        if me.status_code != 200:
            raise GithubError(f"Token validation failed: {me.status_code} {me.text}")
        my_login = me.json()["login"]
        owner_is_user = (owner.lower() == my_login.lower())

        existing = _repo_exists(client, req.token, owner, repo)
        created = False
        if not existing:
            if not req.create_if_missing:
                raise GithubError(f"Repo {owner}/{repo} does not exist and create_if_missing=False")
            created_repo = _create_repo(client, req.token, repo, req.private, owner_is_user, owner)
            existing = created_repo
            created = True

        repo_full_name = existing.get("full_name", f"{owner}/{repo}")
        repo_url = existing.get("html_url", f"https://github.com/{repo_full_name}")
        # If repo was just auto_init'd, default branch is usually 'main'; honour user choice
        target_branch = req.branch or existing.get("default_branch") or "main"

        commits: List[dict] = []

        # Push each terraform file
        base = req.base_path.strip("/")
        for f in req.files:
            path = f"{base}/{f.filename}" if base else f.filename
            commit = _put_file(
                client,
                req.token,
                owner,
                repo,
                path,
                f.content,
                target_branch,
                req.commit_message,
            )
            commits.append(commit)

        # Optional README at repo root
        if req.include_readme:
            readme_content = _build_readme(req.files, extra=req.readme_extra)
            commit = _put_file(
                client,
                req.token,
                owner,
                repo,
                "README.md",
                readme_content,
                target_branch,
                req.commit_message,
            )
            commits.append(commit)

    return GithubPushResponse(
        repo_url=repo_url,
        repo_full_name=repo_full_name,
        branch=target_branch,
        commits=commits,
        created_repo=created,
        files_written=len(commits),
    )
